### ISSUE TITLE
is API rate limit based on token or token & ip?

### ISSUE THREAD

**Issue by passos** [blockcypher/java-client#13]
Hi 
I am currently writing an Android application that allow user to manage their digital currency wallet. It's possible that user could have multiple btc/eth wallet that need to query/update the latest balance when application is launched.

I am wondering is api rate limit based on token or ip? If it's based on token then all my users will use same token to query the wallet balance which will apparently reach the per second rate limit very quickly. If my App has more than 1000 users even the highest plan won't work in this case.

What should I do?

**Comment by quentinlesceller** [comment]
API is rate limited based on the token.
