### ISSUE TITLE
Getting error when signing transaction with multiple input

### ISSUE THREAD

**Issue by tranchiendang** [blockcypher/java-client#15]
After signing transaction with multiple input, i encountered this issue:

> Error reading signatures and pubkeys: Number of signatures and public keys should be a multiple of input count

Is there any suggestion? @matthieu

**Comment by erakadjiev** [comment]
@tranchiendang Assuming that you are asking about a standard (non-multisig) transaction, you need to provide 1 signature and 1 public key for **each** input.
For example, if you have N inputs from the same address, you simply need to provide the N signatures and the same pubkey N times.

**Comment by quentinlesceller** [comment]
Closing.
