### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by lclc** [blockcypher/java-client#9]
Hi guys,
The repo is missing a license file. AFAIK if there is no license it's proprietary therefore nobody can use it without your explicit permission.

Maybe this is helpful: https://choosealicense.com/
Bitcoin Core (and many other Bitcoin projects) use MIT.

**Comment by quentinlesceller** [comment]
Fixed by 4fc54903e0064f4ebcc829f42e39e4fb400a528c. Closing.
